config/routes.rb
# gui controllers can't be namespaced because redmine doesn't use link_to properly with a prepended '/'
scope :hourglass, as: :hourglass do
  scope :ui, as: :ui, controller: :hourglass_ui do
    root action: :index
    get 'time_logs'
    get 'time_logs/new', action: :new_time_logs
    get 'time_logs/:id/edit', action: :edit_time_logs, as: :edit_time_logs
    get 'time_logs/edit', action: :bulk_edit_time_logs, as: :bulk_edit_time_logs
    get 'time_logs/:id/book', action: :book_time_logs, as: :book_time_logs
    get 'time_logs/book', action: :bulk_book_time_logs, as: :bulk_book_time_logs
    get 'time_bookings'
    get 'time_bookings/new', action: :new_time_bookings
    get 'time_bookings/:id/edit', action: :edit_time_bookings, as: :edit_time_bookings
    get 'time_bookings/edit', action: :bulk_edit_time_bookings, as: :bulk_edit_time_bookings
    get 'report'
    get 'time_trackers'
    get 'time_trackers/:id/edit', action: :edit_time_trackers, as: :edit_time_trackers
    get 'time_trackers/edit', action: :bulk_edit_time_trackers, as: :bulk_edit_time_trackers
    get 'context_menu'

    get 'api_docs'
  end

  scope :completion, as: :completion, controller: :hourglass_completion do
    get 'issues'
    get 'activities'
    get 'users'
  end

  resources :queries, controller: :hourglass_queries, except: [:show, :index]

  scope :import, as: :import, controller: :hourglass_import do
    put 'redmine_time_tracker_plugin'
  end
end

resources :projects, only: [] do
  member do
    scope :hourglass, as: :hourglass do
      post 'settings', controller: :hourglass_projects
    end
  end
  nested do
    scope :hourglass, as: :hourglass do
      resources :queries, controller: :hourglass_queries, only: [:new, :create]
    end
  end
end

namespace :hourglass do
  resources :time_trackers, except: [:new, :edit, :create] do
    collection do
      post 'bulk_update'
      delete 'bulk_destroy'
      post 'start'
      put 'add_hint'
    end
    delete 'stop', on: :member
  end
  resources :time_logs, except: [:new, :edit] do
    collection do
      post 'bulk_create'
      post 'bulk_update'
      delete 'bulk_destroy'
      post 'bulk_book'
      post 'join'
    end
    member do
      post 'book'
      post 'split'
    end
  end
  resources :time_bookings, except: [:new, :edit] do
    collection do
      post 'bulk_create'
      post 'bulk_update'
      delete 'bulk_destroy'
    end
  end

  mount Rswag::Api::Engine => '/api-docs'
end


mount Hourglass::Assets.instance, at: File.join(Hourglass::Assets.assets_directory_path) unless Rails.env.production?

app/models/hourglass/time_booking.rb
module Hourglass
  class TimeBooking < ApplicationRecord
    include Namespace
    include ProjectIssueSyncing

    belongs_to :time_log
    belongs_to :time_entry, dependent: :destroy
    has_one :user, through: :time_log
    has_one :project, through: :time_entry
    has_one :issue, through: :time_entry
    has_one :activity, through: :time_entry
    has_one :fixed_version, through: :issue
    has_many :custom_values, through: :time_entry

    accepts_nested_attributes_for :time_entry
    accepts_nested_attributes_for :time_log

    after_initialize :fix_nil_hours
    after_validation :filter_time_entry_invalid_error
    after_save :save_custom_field_values

    validates_presence_of :time_log, :time_entry, :start, :stop
    validate :stop_is_valid
    validates_associated :time_entry

    delegate :id, to: :issue, prefix: true, allow_nil: true
    delegate :id, to: :activity, prefix: true, allow_nil: true
    delegate :id, to: :project, prefix: true, allow_nil: true
    delegate :id, to: :user, prefix: true, allow_nil: true
    delegate :comments, :comments=, :hours, :project_id=, :save_custom_field_values, to: :time_entry, allow_nil: true

    scope :visible, lambda { |*args| joins(:project).where(projects: {id: visible_condition(args.shift || User.current, *args)})
    }

    def update(args = {})
      if args[:time_entry_attributes].present? && time_entry.present?
        args[:time_entry_attributes].merge! id: time_entry_id
      end
      if args[:time_log_attributes].present? && time_log.present?
        args[:time_log_attributes].merge! id: time_log_id
      end
      super args
    end

    def rounding_carry_over
      (stop - time_log.stop).to_i
    end

    def as_json(args = {})
      includes = [:time_entry]
      includes << :time_log if include_time_log?
      super({include: includes}.deep_merge args)
    end

    def include_time_log!
      @include_time_log = true
    end

    def time_tracker_params
      {issue_id: issue_id, project_id: project_id, activity_id: activity_id, comments: comments}
    end

    private
    def self.visible_condition(user, _options = {})
      project_ids = Project.allowed_to(user, :hourglass_view_booked_time).pluck :id
      project_ids += Project.allowed_to(user, :hourglass_view_own_booked_time).pluck :id
      project_ids.uniq
    end

    def fix_nil_hours
      time_entry.hours ||= 0 if time_entry && time_entry.activity_id.blank? #redmine sets hours to nil, if it's 0 on initializing
    end

    def filter_time_entry_invalid_error
      self.errors.delete(:time_entry)
      # self.errors.messages.transform_keys! {|k| k == :'time_entry.base' ? :base : k}
    end

    def stop_is_valid
      #this is different from the stop validation of time log
      errors.add :stop, :invalid if stop.present? && start.present? && stop < start
    end

    def include_time_log?
      @include_time_log
    end
  end
end

app/controllers/chronos/time_booking_controller.rb
module Chronos
  class TimeBookingController < ApiBaseController
    accept_api_auth :index, :show, :update, :destroy
    before_action :get_time_booking, only: [:show, :update, :destroy]

    def index
      respond_with_success Chronos::TimeBooking.all
    end

    def show
      respond_with_success @time_booking
    end

    def update
      if @time_booking.update time_booking_params
        respond_with_success
      else
        respond_with_error :bad_request, @time_booking.errors.full_messages
      end
    end

    def destroy
      @time_booking.destroy
      if @time_booking.destroyed?
        respond_with_success
      else
        respond_with_error :internal_server_error, I18n.t('chronos.api.time_booking.errors.destroy_failed')
      end
    end

    private
    def time_booking_params
      params.require(:time_booking).permit(:start, :stop, time_entry_arguments: [:comments, :project_id, :issue_id, :activity_id])
    end

    def get_time_booking
      @time_booking = time_booking_from_id
      respond_with_error :not_found, I18n.t('chronos.api.time_booking.errors.not_found') unless @time_booking.present?
    end

    def time_booking_from_id
      Chronos::TimeBooking.find_by id: params[:id]
    end
  end
end

app/controllers/concerns/hourglass_ui/overview.rb
module HourglassUi
  module Overview
    extend ActiveSupport::Concern

    included do
      menu_item :hourglass_overview, only: :index
    end

    def index
      authorize :'hourglass/ui', :view?
      @time_tracker = User.current.hourglass_time_tracker || Hourglass::TimeTracker.new

      @time_log_list_arguments = index_page_list_arguments :time_logs do |time_log_query|
        time_log_query.add_filter 'booked', '!', [true]
        time_log_query.column_names = time_log_query.default_columns_names - [:booked?]
      end
      @time_booking_list_arguments = index_page_list_arguments :time_bookings
    end

    private
    def index_page_list_arguments(query_identifier)
      query = query_class_map[query_identifier].new name: '_'
      query.group_by = :start
      query.add_filter 'date', 'w+lw', [true]
      query.add_filter 'user_id', '=', [User.current.id.to_s]
      yield query if block_given?
      params[:sort] = params["#{query_identifier}_sort"]
      @sort_default = [%w(date desc)]
      sort_update query.sortable_columns, "#{sort_name}_#{query_identifier}"
      query.sort_criteria = @sort_criteria.to_a
      list_arguments(query, per_page: 15, page_param: "#{query_identifier}_page").merge action_name: query_identifier.to_s, hide_per_page_links: true, sort_param_name: "#{query_identifier}_sort"
    end
  end
end

app/controllers/concerns/hourglass_ui/time_bookings.rb
module HourglassUi
  module TimeBookings
    extend ActiveSupport::Concern

    included do
      menu_item :hourglass_time_bookings, only: :time_bookings
    end

    def time_bookings
      list_records Hourglass::TimeBooking
      build_chart_query
    end

    def new_time_bookings
      authorize Hourglass::TimeBooking, :create?
      now = Time.now.change(sec: 0)
      duration = Hourglass::DateTimeCalculations.in_hours Hourglass::DateTimeCalculations.round_minimum
      time_booking = Hourglass::TimeBooking.new start: now, stop: now + duration.hours,
                                                time_entry_attributes: {hours: duration}
      render 'hourglass_ui/time_bookings/new', locals: {time_booking: time_booking}, layout: false
    end

    def edit_time_bookings
      record_form Hourglass::TimeBooking
    end

    def bulk_edit_time_bookings
      bulk_record_form Hourglass::TimeBooking
    end

    def report
      @query_identifier = :time_bookings
      list_records Hourglass::TimeBooking
      @list_arguments[:entries] = @list_arguments[:entries].offset(nil).limit(nil)
      build_chart_query
      render layout: false
    end
  end
end

app/controllers/concerns/hourglass_ui/time_logs.rb
module HourglassUi
  module TimeLogs
    extend ActiveSupport::Concern

    included do
      menu_item :hourglass_time_logs, only: :time_logs
    end

    def time_logs
      list_records Hourglass::TimeLog
    end

    def new_time_logs
      authorize Hourglass::TimeLog, :create?
      now = Time.now.change(sec: 0)
      time_log = Hourglass::TimeLog.new start: now, stop: now + Hourglass::DateTimeCalculations.round_minimum
      render 'hourglass_ui/time_logs/new', locals: {time_log: time_log}, layout: false
    end

    def edit_time_logs
      record_form Hourglass::TimeLog
    end

    def bulk_edit_time_logs
      bulk_record_form Hourglass::TimeLog
    end

    def book_time_logs
      record_form Hourglass::TimeLog, action: :book?, template: :book
    end

    def bulk_book_time_logs
      bulk_record_form Hourglass::TimeLog, action: :book?, template: :book
    end
  end
end

app/controllers/concerns/hourglass_ui/time_trackers.rb
module HourglassUi
  module TimeTrackers
    extend ActiveSupport::Concern

    included do
      menu_item :hourglass_time_trackers, only: :time_trackers
    end

    def time_trackers
      list_records Hourglass::TimeTracker
      render 'hourglass_ui/query_view'
    end

    def edit_time_trackers
      record_form Hourglass::TimeTracker
    end

    def bulk_edit_time_trackers
      bulk_record_form Hourglass::TimeTracker
    end
  end
end

app/controllers/hourglass/time_bookings_controller.rb
module Hourglass
  class TimeBookingsController < ApiBaseController
    accept_api_auth :index, :show, :create, :bulk_create, :update, :bulk_update, :destroy, :bulk_destroy

    def index
      list_records Hourglass::TimeBooking
    end

    def show
      respond_with_success authorize time_booking_from_id
    end

    def create
      time_log, time_booking = nil
      ActiveRecord::Base.transaction do
        time_log = Hourglass::TimeLog.create create_time_log_params
        raise ActiveRecord::Rollback unless time_log.persisted?
        time_booking = authorize time_log.book time_entry_params
        raise ActiveRecord::Rollback unless time_booking.persisted?
        respond_with_success time_log: time_log, time_booking: time_booking
      end
      error_messages = time_log.errors.full_messages
      error_messages += time_booking.errors.full_messages if time_booking
      respond_with_error :bad_request, error_messages, array_mode: :sentence
    end

    def bulk_create
      bulk do |_, params|
        result = nil
        ActiveRecord::Base.transaction do
          result = Hourglass::TimeLog.create create_time_log_params params
          raise ActiveRecord::Rollback unless result.persisted?
          result = authorize result.book time_entry_params(params).except(:user_id)
          raise ActiveRecord::Rollback unless result.persisted?
          result.include_time_log!
        end
        result
      end
    end

    def update
      attributes = {time_entry_attributes: time_entry_params}
      attributes[:time_log_attributes] = attributes[:time_entry_attributes].slice(:user_id) if attributes[:time_entry_attributes][:user_id]
      do_update time_booking_from_id, attributes
    end

    def bulk_update
      authorize Hourglass::TimeBooking
      bulk do |id, params|
        attributes = {time_entry_attributes: time_entry_params(params)}
        attributes[:time_log_attributes] = attributes[:time_entry_attributes].slice(:user_id) if attributes[:time_entry_attributes][:user_id]
        authorize_update time_booking_from_id(id), attributes
      end
    end

    def destroy
      authorize(time_booking_from_id).destroy
      respond_with_success
    end

    def bulk_destroy
      authorize Hourglass::TimeBooking
      bulk do |id|
        authorize(time_booking_from_id id).destroy
      end
    end

    private
    def create_time_log_params(params_hash = params.require(:time_booking))
      params_hash.permit(:start, :stop, :comments, :user_id)
    end

    def time_entry_params(params_hash = params.require(:time_booking))
      params_hash.permit(:comments, :project_id, :issue_id, :activity_id, :user_id,
                         custom_field_values: custom_field_keys(params_hash))
    end

    def time_booking_from_id(id = params[:id])
      Hourglass::TimeBooking.find id
    end
  end
end

app/controllers/hourglass_ui_controller.rb
class HourglassUiController < ApplicationController
  helper QueriesHelper
  helper IssuesHelper
  helper SortHelper
  helper ContextMenusHelper
  helper CustomFieldsHelper
  helper Hourglass::ApplicationHelper
  helper Hourglass::UiHelper
  helper Hourglass::ListHelper
  helper Hourglass::ChartHelper
  helper Hourglass::ReportHelper

  include AuthorizationConcern
  include SortConcern
  include QueryConcern
  include ListConcern

  include HourglassUi::Overview
  include HourglassUi::TimeLogs
  include HourglassUi::TimeBookings
  include HourglassUi::TimeTrackers


  before_action :require_login

  def context_menu
    list_type = get_list_type
    @records = Hourglass.const_get(list_type.classify).find params[:ids]
    render "hourglass_ui/#{list_type}/context_menu", layout: false
  end

  def api_docs
  end

  private
  def get_list_type
    list_type = %w(time_bookings time_logs time_trackers).select {|val| val == params[:list_type]}.first
    render_403 unless list_type
    list_type
  end
end

app/views/hourglass_ui/time_bookings/_list_entry_actions.slim
- time_tracker = User.current.hourglass_time_tracker

- if time_tracker and (not @once)
  = render partial: 'hooks/time_tracker/start_dialog_content', locals: {time_tracker: time_tracker}
  - @once = (not nil)

= link_to '', start_hourglass_time_trackers_path, class: 'icon-hourglass-continue js-hourglass-remote js-start-tracker', title: t('hourglass.ui.time_bookings.button_continue'),
        remote: true, method: 'post',
        data: {params: {time_tracker: time_booking.time_tracker_params}.to_param}

- if policy(time_booking).change?
  = link_to '', hourglass_ui_edit_time_bookings_path(time_booking), class: 'icon icon-edit js-show-inline-form', title: t(:button_edit), remote: true, data: {type: 'html'}
- if policy(time_booking).destroy?
  = link_to '', hourglass_time_booking_path(time_booking), class: 'icon icon-del js-hourglass-remote', title: t(:button_delete), remote: true, method: :delete, data: {confirm: t(:text_are_you_sure)}

app/views/hourglass_ui/time_bookings/context_menu.slim
- ids = @records.map(&:id)
ul
  li = context_menu_link t(:button_edit), hourglass_ui_bulk_edit_time_bookings_path(ids: ids), class: 'icon icon-edit js-show-inline-form-multi', title: t(:button_edit), remote: true, data: {type: 'html'}, disabled: !@records.all? { |time_booking| policy(time_booking).change? }
  li = context_menu_link t(:button_delete), @records.length == 1 ? hourglass_time_booking_path(@records.first) : bulk_destroy_hourglass_time_bookings_path(time_bookings: ids), class: 'icon icon-del js-hourglass-remote', title: t(:button_delete), remote: true, method: :delete, data: {confirm: t(:text_are_you_sure)}, disabled: !@records.all? { |time_booking| policy(time_booking).destroy? }

app/views/hourglass_ui/time_bookings/edit.slim
- time_bookings.each do |time_booking|
  = form_for time_booking, as: 'time_booking', remote: true, html: {id: "edit_time_booking_#{time_booking.id}", class: 'edit-time-booking-form js-hourglass-remote js-validate-form js-check-splitting', data: {time_log_id: time_booking.time_log_id, form_type: 'edit-time-booking', id_for_bulk_edit: time_booking.id}} do |f|
    .form-row
      = form_field :start, f, time_booking, disabled: !policy(time_booking).change?(:start), validate_limit: true, allow_zero_duration: true, not_in_multi: true
      = form_field :stop, f, time_booking, disabled: !policy(time_booking).change?(:stop), validate_limit: true, allow_zero_duration: true, not_in_multi: true
      = form_field :duration, f, time_booking, disabled: !policy(time_booking).change?(:stop), not_in_multi: true
      - rounding_disabled = Hourglass::SettingsStorage[:round_sums_only, project: time_booking.project]
      .form-field class=('hidden' if rounding_disabled)
        .label
          = label :time_booking, :round, t(:field_round), title: t('hourglass.ui.time_bookings.round_hint')
        .input
          = check_box :time_booking, :round, checked: Hourglass::SettingsStorage[:round_default, project: time_booking.project], disabled: rounding_disabled
      = form_field :project, f, time_booking, disabled: !policy(time_booking).change?, required: true
      = form_field :activity, f, time_booking, disabled: !policy(time_booking).change?, required: true
      = form_field :issue, f, time_booking, disabled: !policy(time_booking).change?
      = form_field :comments, f, time_booking, disabled: !policy(time_booking).change?
      = form_field :user_id, f, time_booking, required: true, disabled: !policy(time_booking).change?(:user_id)
      - time_booking.time_entry.custom_field_values.each do |value|
        .form-field = custom_field_tag_with_label :'time_booking', value
      .form-field
        .input
          = f.submit t(:button_update)
          button type='button' class='js-bulk-edit hidden' data-url=bulk_update_hourglass_time_bookings_path data-name='time_bookings'
            = t('hourglass.ui.lists.button_update_all')
          = link_to t(:button_cancel), '#', class: 'js-hide-inline-form'

app/views/hourglass_ui/time_bookings/new.slim
= form_for time_booking, as: 'time_booking', remote: true, html: {id: 'new_time_booking', class: 'new-time-booking-form js-hourglass-remote js-validate-form', data: {form_type: 'new-time-booking'}} do |f|
  - index = Time.now.to_i
  .form-row
    = form_field :start, f, time_booking, css_classes: %w(js-picker-with-date), id: "time_booking_#{index}_start"
    = form_field :stop, f, time_booking, css_classes: %w(js-picker-with-date), id: "time_booking_#{index}_stop"
    = form_field :duration, f, time_booking
    - rounding_disabled = Hourglass::SettingsStorage[:round_sums_only]
    .form-field class=('hidden' if rounding_disabled)
      .label
        = label :time_booking, :round, t(:field_round), title: t('hourglass.ui.time_bookings.round_hint')
      .input
        = check_box :time_booking, :round, checked: Hourglass::SettingsStorage[:round_default]
    = form_field :project, f, time_booking, required: true
    = form_field :activity, f, time_booking, required: true
    = form_field :issue, f, time_booking
    = form_field :comments, f, time_booking
    = form_field :user_id, f, time_booking, required: true
    - time_booking.build_time_entry.custom_field_values.each do |value|
      .form-field = custom_field_tag_with_label :'time_booking', value
    .form-field
      .input
        = f.submit t(:button_create)
        button type='button' class='js-bulk-edit hidden' data-url=bulk_create_hourglass_time_bookings_path data-name='time_bookings'
          = t('hourglass.ui.lists.button_create_all')
        = link_to t(:button_cancel), '#', class: 'js-hide-inline-form'