config/routes.rb
# gui controllers can't be namespaced because redmine doesn't use link_to properly with a prepended '/'
scope :hourglass, as: :hourglass do
  scope :ui, as: :ui, controller: :hourglass_ui do
    root action: :index
    get 'time_logs'
    get 'time_logs/new', action: :new_time_logs
    get 'time_logs/:id/edit', action: :edit_time_logs, as: :edit_time_logs
    get 'time_logs/edit', action: :bulk_edit_time_logs, as: :bulk_edit_time_logs
    get 'time_logs/:id/book', action: :book_time_logs, as: :book_time_logs
    get 'time_logs/book', action: :bulk_book_time_logs, as: :bulk_book_time_logs
    get 'time_bookings'
    get 'time_bookings/new', action: :new_time_bookings
    get 'time_bookings/:id/edit', action: :edit_time_bookings, as: :edit_time_bookings
    get 'time_bookings/edit', action: :bulk_edit_time_bookings, as: :bulk_edit_time_bookings
    get 'report'
    get 'time_trackers'
    get 'time_trackers/:id/edit', action: :edit_time_trackers, as: :edit_time_trackers
    get 'time_trackers/edit', action: :bulk_edit_time_trackers, as: :bulk_edit_time_trackers
    get 'context_menu'

    get 'api_docs'
  end

  scope :completion, as: :completion, controller: :hourglass_completion do
    get 'issues'
    get 'activities'
    get 'users'
  end

  resources :queries, controller: :hourglass_queries, except: [:show, :index]

  scope :import, as: :import, controller: :hourglass_import do
    put 'redmine_time_tracker_plugin'
  end
end

resources :projects, only: [] do
  member do
    scope :hourglass, as: :hourglass do
      post 'settings', controller: :hourglass_projects
    end
  end
  nested do
    scope :hourglass, as: :hourglass do
      resources :queries, controller: :hourglass_queries, only: [:new, :create]
    end
  end
end

namespace :hourglass do
  resources :time_trackers, except: [:new, :edit, :create] do
    collection do
      post 'bulk_update'
      delete 'bulk_destroy'
      post 'start'
      put 'add_hint'
    end
    delete 'stop', on: :member
  end
  resources :time_logs, except: [:new, :edit] do
    collection do
      post 'bulk_create'
      post 'bulk_update'
      delete 'bulk_destroy'
      post 'bulk_book'
      post 'join'
    end
    member do
      post 'book'
      post 'split'
    end
  end
  resources :time_bookings, except: [:new, :edit] do
    collection do
      post 'bulk_create'
      post 'bulk_update'
      delete 'bulk_destroy'
    end
  end

  mount Rswag::Api::Engine => '/api-docs'
end


mount Hourglass::Assets.instance, at: File.join(Hourglass::Assets.assets_directory_path) unless Rails.env.production?

app/views/hourglass_ui/forms/fields/_activity.slim
.form-field
  .label
    = form.label :activity_id
  .input
    = form.collection_select :activity_id, TimeEntryActivity.applicable(entry.project), :id, :name, { include_blank: true }, disabled: local_assigns[:disabled], required: local_assigns[:required]

app/views/hourglass_ui/forms/fields/_comments.slim
.form-field
  .label
    = form.label :comments
  .input
    = form.text_field :comments, size: '30', maxlength: 255, disabled: local_assigns[:disabled]

app/views/hourglass_ui/forms/fields/_duration.slim
.form-field
  .label
    = form.label :duration
  .input
    = form.text_field :duration, size: '10', name: nil, value: entry.hours, disabled: local_assigns[:disabled], class: css_classes('js-duration', ('js-not-in-multi' if local_assigns[:not_in_multi].present?))

app/views/hourglass_ui/forms/fields/_issue.slim
.form-field
  .label
    = form.label :issue_id, for: 'issue_text'
    - if local_assigns[:with_link]
      = link_to '', issue_path(id: entry.issue_id || ''), class: css_classes('icon icon-link', ('hidden' unless entry.issue))
  .input
    = text_field_tag nil, issue_label_for(entry.issue), id: 'issue_text', size: '15', disabled: local_assigns[:disabled], class: 'js-issue-autocompletion js-linked-with-hidden'
    = form.hidden_field :issue_id

app/views/hourglass_ui/forms/fields/_project.slim
.form-field
  .label
    = form.label :project_id
    - if local_assigns[:with_link]
      = link_to '', project_path(id: entry.project_id || ''), class: css_classes('icon icon-link', ('hidden' unless entry.project))
  .input
    = form.select :project_id, projects_for_project_select(entry.project), { include_blank: true }, disabled: local_assigns[:disabled], required: local_assigns[:required]

app/views/hourglass_ui/forms/fields/_start.slim
= render partial: 'hourglass_ui/forms/fields/start_stop', locals: local_assigns.merge(field: :start)

app/views/hourglass_ui/forms/fields/_start_stop.slim
.form-field
  .label
    = form.label field
  .input
    - options = {disabled: local_assigns[:disabled], class: css_classes(local_assigns[:css_classes],
            ('js-validate-limit' if local_assigns[:validate_limit].present?),
            ('js-allow-zero-duration' if local_assigns[:allow_zero_duration].present?),
            ('js-not-in-multi' if local_assigns[:not_in_multi].present?))}
    - options[:id] = local_assigns[:id] if local_assigns[:id].present?
    = form.text_field field, name: nil, id: nil, value: entry[field] && format_time(entry[field]),
            disabled: local_assigns[:disabled], class: css_classes('js-linked-with-hidden js-time-field', ('js-not-in-multi' if local_assigns[:not_in_multi].present?))
    = form.hidden_field field, options.merge(value: entry[field].iso8601)

app/views/hourglass_ui/forms/fields/_stop.slim
= render partial: 'hourglass_ui/forms/fields/start_stop', locals: local_assigns.merge(field: :stop)

app/views/hourglass_ui/forms/fields/_user_id.slim
.form-field
  .label
    = form.label :user_id
  .input
    - project = entry && entry.respond_to?(:project) && entry.project || nil
    = form.select :user_id, options_from_collection_for_select(user_collection(project), :id, :name, entry.user_id || User.current.id), { include_blank: true }, disabled: local_assigns[:disabled], required: local_assigns[:required]